"""Generate the lettered logo (octopus + "Omni / Queue" in a 5x7 pixel font).

Run: python tools/make_logo_text.py
Writes src/omniqueue/static/logo_text.svg (deep teal lettering, light theme)
and logo_text_dark.svg (light teal lettering, dark theme). The hand-drawn
smooth-lettered originals are kept as logo_text_smooth*.svg.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_logo import H as OCT_H, W as OCT_W, g as octopus  # noqa: E402

# 5x7 pixel glyphs ('#' = ink). Lowercase letters sit on the same baseline (row 6).
GLYPHS = {  # bold: two-pixel strokes; baseline is row 6, Q has a one-row descender
    "O": [".#####.", "##...##", "##...##", "##...##", "##...##", "##...##", ".#####."],
    "Q": [".#####.", "##...##", "##...##", "##...##", "##.#.##", "##..###", ".#####.", "......#"],
    "m": [".......", ".......", "##.##..", "#######", "##.#.##", "##.#.##", "##.#.##"],
    "n": ["......", "......", "##.##.", "###.##", "##..##", "##..##", "##..##"],
    "i": ["##", "..", "##", "##", "##", "##", "##"],
    "u": ["......", "......", "##..##", "##..##", "##..##", "##.###", ".##.##"],
    "e": ["......", "......", ".####.", "##..##", "######", "##....", ".#####"],
}
SCALE = 3  # one glyph pixel = 3 canvas units, so the lettering matches the 60-unit octopus
GAP = 1  # glyph pixels between letters
LIGHT_INK, DARK_INK = "#26564f", "#7fb5b0"


def text_pixels(text: str, x0: int, y0: int) -> tuple[list[tuple[int, int, int, int]], int]:
    """Rects (x, y, w, h) in canvas units for `text` starting at (x0, y0); returns rects and width."""
    rects = []
    x = x0
    for ch in text:
        glyph = GLYPHS[ch]
        for gy, row in enumerate(glyph):
            for gx, px in enumerate(row):
                if px == "#":
                    rects.append((x + gx * SCALE, y0 + gy * SCALE, SCALE, SCALE))
        x += (len(glyph[0]) + GAP) * SCALE
    return rects, x - GAP * SCALE - x0


def build(ink: str) -> str:
    text_x = OCT_W + 8
    line_h = 7 * SCALE
    omni, omni_w = text_pixels("Omni", text_x + 3 * SCALE, 5)  # "Omni" indented like the original
    queue, queue_w = text_pixels("Queue", text_x, 5 + line_h + SCALE)
    width = max(text_x + 3 * SCALE + omni_w, text_x + queue_w) + 4
    height = OCT_H
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'width="{width * 8}" height="{height * 8}" shape-rendering="crispEdges">',
        "<!-- OmniQueue lettered logo, generated by tools/make_logo_text.py -->",
    ]
    # octopus: merge horizontal runs of one colour into single rects
    for y in range(OCT_H):
        x = 0
        while x < OCT_W:
            c = octopus.get((x, y))
            if c is None:
                x += 1
                continue
            run = 1
            while octopus.get((x + run, y)) == c:
                run += 1
            out.append(f'<rect x="{x}" y="{y}" width="{run}" height="1" fill="{c}"/>')
            x += run
    for x, y, w, h in omni + queue:
        out.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{ink}"/>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    static = Path(__file__).resolve().parent.parent / "src" / "omniqueue" / "static"
    (static / "logo_text.svg").write_text(build(LIGHT_INK))
    (static / "logo_text_dark.svg").write_text(build(DARK_INK))
    print("wrote logo_text.svg and logo_text_dark.svg")
