"""Generate the OmniQueue 8-bit octopus logo as SVG.

Run: python tools/make_logo.py
Writes src/omniqueue/static/logo.svg and favicon.svg. Edit SPRITE and re-run.

Legend: '#' outline  'b' body  's' shade  'h' highlight  'o' eye  '@' pupil
        'c' cheek    'd' data packet  'D' packet centre  '.' streaming bit
"""

from __future__ import annotations

from pathlib import Path

SPRITE = [
    "       ##########       ",
    "     ##bbbbbbbbbb##     ",
    "    #bbhhbbbbbbbbbb#    ",
    "   #bbhbbbbbbbbbbbbb#   ",
    "   #bbhbbbbbbbbbbbbb#   ",
    "  #bbbbbbbbbbbbbbbbbb#  ",
    "  #bb#####bbbb#####bb#  ",
    "  #bb#ooo#bbbb#ooo#bb#  ",
    "  #bb#o@o#bbbb#o@o#bb#  ",
    "  #bb#o@o#bbbb#o@o#bb#  ",
    "  #bb#####bbbb#####bb#  ",
    "  #bccbbbbbbbbbbbbccb#  ",
    "   #bbbbbbbbbbbbbbbb#   ",
    "   #bbb#bbb##bbb#bbb#   ",
    "  #bbb##bbb##bbb##bbb#  ",
    " #bbb# #bbb##bbb# #bbb# ",
    "#bbb#  #bbb##bbb#  #bbb#",
    "#bb#   #bb####bb#   #bb#",
    "#ss#   #bb#  #bb#   #ss#",
    "dd##   #bb#  #bb#   ##dd",
    "Dd     #bb#  #bb#     dD",
    "  .    #sb#  #bs#    .  ",
    "        dd    dd        ",
    "        Dd .. dD        ",
]

COLORS = {
    "#": "#0d3b38",  # outline, deep peacock
    "b": "#4f8f8a",  # body teal
    "s": "#3b7672",  # shade
    "h": "#a9cbc8",  # highlight, arctic
    "o": "#fbefdc",  # eye white, lace
    "@": "#0d3b38",  # pupil
    "c": "#e2856c",  # cheek, coral
    "d": "#b39a4b",  # data packet, mustard
    "D": "#fbefdc",  # packet centre
    ".": "#c8b47c",  # streaming bit, sage
}

H = len(SPRITE)
W = len(SPRITE[0])
assert all(len(r) == W for r in SPRITE), [i for i, r in enumerate(SPRITE) if len(r) != W]
assert W == H == 24


def svg(background: str | None = None, pad: int = 0) -> str:
    size = W + 2 * pad
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" '
        f'width="{size * 8}" height="{size * 8}" shape-rendering="crispEdges">',
        "<!-- OmniQueue octopus, generated by tools/make_logo.py -->",
    ]
    if background:
        out.append(f'<rect width="{size}" height="{size}" rx="{size / 6:.1f}" fill="{background}"/>')
    for y, row in enumerate(SPRITE):
        x = 0
        while x < W:  # merge runs of one colour into a single rect
            ch = row[x]
            if ch == " ":
                x += 1
                continue
            run = 1
            while x + run < W and row[x + run] == ch:
                run += 1
            out.append(f'<rect x="{x + pad}" y="{y + pad}" width="{run}" height="1" fill="{COLORS[ch]}"/>')
            x += run
    out.append("</svg>")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    static = Path(__file__).resolve().parent.parent / "src" / "omniqueue" / "static"
    (static / "logo.svg").write_text(svg())
    (static / "favicon.svg").write_text(svg("#073a34", pad=2))
    print("wrote", static / "logo.svg", "and", static / "favicon.svg")
