"""Generate the OmniQueue pixel octopus logo as SVG.

Run: python tools/make_logo.py
Writes src/omniqueue/static/logo.svg and favicon.svg. The body is a circle plus
eight tapered arms drawn as polylines; shading is derived automatically and each
arm tip holds a ball in its own colour (one colour per data source).
"""

from __future__ import annotations

import math
from pathlib import Path

W = H = 40
BODY, SHADE, HI = "#4f8f8a", "#2f6a66", "#7fb5b0"
EYE, EYE_HI, MOUTH = "#0d3b38", "#fbefdc", "#2f6a66"
BALLS = ["#e2856c", "#b39a4b", "#a9cbc8", "#c8b47c", "#f3c6b6", "#8fa35a", "#b07a8a", "#fbefdc"]
BALL_HI = "#fbefdc"

g: dict[tuple[int, int], str] = {}


def put(x: int, y: int, c: str) -> None:
    if 0 <= x < W and 0 <= y < H:
        g[(x, y)] = c


def disc(cx: float, cy: float, r: float, c: str) -> None:
    for y in range(int(cy - r - 1), int(cy + r + 2)):
        for x in range(int(cx - r - 1), int(cx + r + 2)):
            if (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2 <= r * r:
                put(x, y, c)


def arm(points: list[tuple[float, float]], r0: float, r1: float) -> None:
    """Polyline through `points`, radius tapering from r0 at the base to r1 at the tip."""
    total = sum(math.dist(a, b) for a, b in zip(points, points[1:]))
    done = 0.0
    for a, b in zip(points, points[1:]):
        seg = math.dist(a, b)
        steps = max(1, int(seg * 3))
        for i in range(steps + 1):
            t = i / steps
            frac = (done + seg * t) / total
            r = r0 + (r1 - r0) * frac
            disc(a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, r, BODY)
        done += seg


def mirror(pts: list[tuple[float, float]]) -> list[tuple[float, float]]:
    return [(W - x, y) for x, y in pts]


# ---- head and central body ---------------------------------------------------------
disc(20, 13, 9.6, BODY)        # head
disc(20, 21.5, 7.0, BODY)      # body / arm crown

# ---- arms: base at the body, curling outward (left side; mirrored) -----------------
LEFT_ARMS = [
    [(14, 17), (9, 13), (5, 8), (5, 4)],             # up-left, reaches up
    [(13, 22), (7, 22), (3, 19), (2, 15)],           # left, curls up
    [(15, 26), (10, 30), (6, 34), (3, 36)],          # down-left outer, curls out
    [(18, 28), (17, 33), (14, 37), (11, 38)],        # down-left inner, curls out
]
for pts in LEFT_ARMS:
    arm(pts, 3.0, 1.6)
    arm(mirror(pts), 3.0, 1.6)

# ---- shading: darker tone along the lower and right edges ---------------------------
for (x, y), c in list(g.items()):
    if c == BODY and (g.get((x, y + 1)) is None or g.get((x + 1, y)) is None):
        g[(x, y)] = SHADE
# a lighter highlight on the upper-left of the head
for x, y in ((15, 6), (16, 5), (17, 5), (14, 7), (13, 8), (13, 9)):
    put(x, y, HI)

# ---- face ------------------------------------------------------------------------------
for ex in (15, 23):
    for dx in range(2):
        for dy in range(3):
            put(ex + dx, 12 + dy, EYE)
    put(ex, 12, EYE_HI)
for x in range(18, 22):
    put(x, 18, MOUTH)
put(17, 17, MOUTH)
put(22, 17, MOUTH)

# ---- balls in the arm tips, one colour per source ------------------------------------
def ball(cx: float, cy: float, colour: str) -> None:
    disc(cx, cy, 2.2, colour)
    put(int(cx - 1.5), int(cy - 1.5), BALL_HI if colour != BALL_HI else "#c8b47c")


for i, pts in enumerate(LEFT_ARMS):
    (x0, y0), (x1, y1) = pts[-2], pts[-1]
    d = math.dist(pts[-2], pts[-1]) or 1
    ext = 2.6
    cx, cy = x1 + (x1 - x0) / d * ext, y1 + (y1 - y0) / d * ext
    cx, cy = min(max(cx, 2.2), W / 2 - 2), min(max(cy, 2.2), H - 2.2)
    ball(cx, cy, BALLS[i])
    ball(W - cx, cy, BALLS[i + 4])


def svg(background: str | None = None, pad: int = 0) -> str:
    size = W + 2 * pad
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" '
        f'width="{size * 8}" height="{size * 8}" shape-rendering="crispEdges">',
        "<!-- OmniQueue octopus, generated by tools/make_logo.py -->",
    ]
    if background:
        out.append(f'<rect width="{size}" height="{size}" rx="{size / 6:.1f}" fill="{background}"/>')
    for y in range(H):
        x = 0
        while x < W:
            c = g.get((x, y))
            if c is None:
                x += 1
                continue
            run = 1
            while g.get((x + run, y)) == c:
                run += 1
            out.append(f'<rect x="{x + pad}" y="{y + pad}" width="{run}" height="1" fill="{c}"/>')
            x += run
    out.append("</svg>")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    static = Path(__file__).resolve().parent.parent / "src" / "omniqueue" / "static"
    (static / "logo.svg").write_text(svg())
    (static / "favicon.svg").write_text(svg("#073a34", pad=2))
    sym = {BODY: "b", SHADE: "s", HI: "h", EYE: "@", EYE_HI: "o", MOUTH: "m"}
    for y in range(H):
        print("".join(sym.get(g.get((x, y)), " " if (x, y) not in g else "*") for x in range(W)))
